DETS_TXT: ./cfgs/target_stellantis_jtlab_sync/label_generation/round1/cfgs/ensemble_detections.txt
SAVE_DIR: ./cfgs/target_stellantis_jtlab_sync/label_generation/round1/ps_labels
MASK_DIR: ./cfgs/target_stellantis_jtlab_sync/ps_masks
POSE_DIR: ./cfgs/target_stellantis_jtlab_sync/

DATA_CONFIG_PATH: ./cfgs/dataset_configs/stellantis_dataset_jtlab_sync.yaml
CAMERA: CAM_FRONT
PS_SCORE_TH: # veh,ped,cyc
  POS_TH: [0.05,0.1,0.1]
  NEG_TH: [0.02,0.05,0.05]

ENSEMBLE_KBF:
  DISCARD: [1, 1, 1]
  RADIUS: [1.5, 0.3, 0.2]
  NMS: [0.1, 0.3, 0.1]

TRACKING:
  LOCAL: False
  IMM: False
  VEH_ALL:
    RUNNING:
        SCORE_TH: 0.05
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.3
        ANGLE_TH: -1
    REDUNDANCY:
        SCORE_TH: 0.05
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: -0.3
  VEH_STATIC:
    RUNNING:
        SCORE_TH: 0.05
        MAX_AGE_SINCE_UPDATE: 3
        MIN_HITS_TO_BIRTH: 2
        ASSO: iou_2d
        ASSO_TH: 0.7
        ANGLE_TH: -1
    REDUNDANCY:
        SCORE_TH: 0.05
        MAX_REDUNDANCY_AGE: 2
        ASSO_TH: 0.5
  BIC_ALL:
    RUNNING:
        SCORE_TH: 0.1
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.3
        ANGLE_TH: -1
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: -0.3
  BIC_STATIC:
    RUNNING:
        SCORE_TH: 0.1
        MAX_AGE_SINCE_UPDATE: 3
        MIN_HITS_TO_BIRTH: 2
        ASSO: iou_2d
        ASSO_TH: 0.7
        ANGLE_TH: -1
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 2
        ASSO_TH: 0.5
  PEDESTRIAN:
    RUNNING:
        SCORE_TH: 0.1
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.5
        ANGLE_TH: -1
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: -0.5

TEMPORAL_REFINEMENT:
  TRACK_FILTERING: 
    MIN_NUM_STATIC_VEH_TRACKS: 7
    MIN_NUM_STATIC_BIC_TRACKS: 7
    MIN_NUM_PED_TRACKS: 7  
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_ALL: 3
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_STATIC: 3
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_BIC_ALL: 3
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_BIC_STATIC: 3
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_PED: 1
    USE_STATIC_PED_TRACKS: true
  ROLLING_KBF:
    MIN_STATIC_SCORE: 0.8
    ROLLING_KDE_WINDOW: 10
  PROPAGATE_BOXES:
    MIN_STATIC_TRACKS: 10
    N_EXTRA_FRAMES: 40
    DEGRADE_FACTOR: 0.98
    MIN_SCORE_CLIP: 0.3
