augment3d:
  scale: [0.95, 1.05]
  rotate: [-0.3925, 0.3925]
  translate: 0

model:
  encoders:
    lidar: null
    camera:
      vtransform:
        type: DepthLSSTransform
        image_size: ${image_size}
        xbound: [0.0, 108.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 100.0, 1.0]
  heads:
    object:
      test_cfg:
        nms_type:
          - circle
          - rotate
          - rotate
          - rotate
          - rotate
        nms_scale:
          - [1.0]
          - [1.0]
          - [1.0]
          - [1.0,1.0]
          - [2.5]

lr_config: null
